global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['web:9113']
    metrics_path: /metrics

  - job_name: 'laravel'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:9104']
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: /metrics

  - job_name: 'recommendation_api'
    static_configs:
      - targets: ['recommendation:5000']
    metrics_path: /metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
